service: serverless-airheroes

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  apiKeys:
    - fr24test
  environment:
    TOKEN: ${file(env.yml):token}

package:
  exclude:
    - .git/**
    - node_modules/**
    - spec/**

functions:
  getRecentFlight:
    handler: functions/getRecentFlight/index.handler
    events:
      - http:
          path: fr24/{flight_number}
          method: get
  lexFlightStatus:
    handler: functions/lexFlightStatus/index.handler
    events:
      - http:
          path: lexFlightStatus
          method: get
  lexFlightStatusByName:
    handler: functions/lexFlightStatusByName/index.handler
  lexSubmitClaim:
    handler: functions/lexSubmitClaim/index.handler
  lexFlightTable:
    handler: functions/lexFlightTable/index.handler
